service: dynamodb-crud-api

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-southeast-1'}
  environment:
    DYNAMODB_TABLE_NAME: ${self:custom.postsTableName}
    NODE_ENV: ${env:NODE_ENV}

custom:
  postsTableName: posts-table-${self:provider.stage}

plugins:
  - serverless-iam-roles-per-function
  - serverless-offline
  - serverless-plugin-optimize

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: any
          path: /{proxy+}
    iamRoleStatements:
      - Effect: 'Allow'
        Action:
          - 'dynamodb:GetItem'
          - 'dynamodb:PutItem'
          - 'dynamodb:UpdateItem'
          - 'dynamodb:DeleteItem'
          - 'dynamodb:Scan'
        Resource: !GetAtt PostsTable.Arn

resources:
  Resources:
    PostsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.postsTableName}
        AttributeDefinitions:
          - AttributeName: postId
            AttributeType: S
        KeySchema:
          - AttributeName: postId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
